### ISSUE TITLE
AttributeError: 'LiteralClient' object has no attribute 'llama_index_callback'

### ISSUE THREAD

**Issue by jayita13** [Chainlit/literalai-cookbooks#18]

**Comment by desaxce** [comment]
Hi @jayita13 ! Could you please share the `literalai` version you are using? 

By the looks of it, you are trying to run our `RAG LlamaIndex` cookbook. Were you able to successfully install dependencies with `pip install -r requirements.txt`?

I just tried to run it from scratch and did not face your error.

**Comment by jayita13** [comment]
got resolved after using latest version compatible with chainlit
